name : storage-app-work-flow
on : [push , workflow_dispatch]
jobs :
  deploy-backend-job :
    runs-on : ubuntu-latest    
    steps : 
      - name : make file
        run : touch server.js

      - name : print 
        run : pwd

      - name : print 
        run : ls



  deploy-frontend-job :
    runs-on : ubuntu-latest  
    needs : deploy-backend-job  
    steps : 
      - name : make file
        run : touch index.html

      - name : print 
        run : pwd

      - name : print 
        run : ls      
        
