name : github-workflow
on : [push, workflow_dispatch]
jobs:
  test-my-job:
    env : 
      git-secret : "this is my secret key"
    runs-on : ubuntu-latest
    steps:
      - run : touch my-file
      - uses : actions/checkout@v2
      - run : echo "${{toJson(env)}}"
      - run : echo "${{secrets}}" 
