name : github-workflow
on : [push, workflow_dispatch]
jobs:
  test-my-job:
    env : 
      git-secret : "this is my secret key"
    runs-on : ubuntu-latest
    steps:
      - run : echo ${{ github.token }}
      - run  : "echo${{toJson(secrets)}}"
