name : notice git chage
on : [push , workflow_dispatch]
jobs:
  git-security-notice :
    runs-on : ubuntu-latest
    steps:
      - name : checkout
        run : pwd
      - name : checkout  
        uses : actions/checkout@v6
      - name : print
        run : pwd   
