name : notice git security
on : [push , workflow_dispatch]
jobs:
  git-security-notice :
    env:
     EC2_HOST: "my-server.com"
     EC2_USER: ubuntu
    runs-on : ubuntu-latest
    steps:
      - name : node version
        run : node -v
      - name : checkout
        uses : actions/checkout@v4
        with : 
          node-version : "24"
      - name : context-check
        run : echo "${{toJson(github) }}"   
      - run : echo ${{toJson(env.EC2_USER) }}   
          
      - name : node v check again 
        run : node -v    

