name : my first workFlow
on : push
jobs : 
  my_first_job:
    runs-on : ubuntu-latest
    steps : 
      - name : checkout
        uses : actions/checkout@v3
      - name : ls
        run : ls
      -  name : make file
         run : touch app.js 
      - name : device details 
        run : sudo dmidecode -t memory



