name : notice git chage
on : [push , workflow_dispatch]
jobs:
  git-security-notice :
    runs-on : ubuntu-latest
    steps:
      - name : node version
        run : node -v
      - name : checkout
        uses : actions/checkout@v4
        with : 
          node-version : "24"
      - name : context-check
        run : echo "${{toJson(github) }}"   
      - run : echo ${{3  <  2}}   
          
      - name : node v check again 
        run : node -v    

